name: Node.js CI
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Code analysis & Test
        run: npm run ciall
